### ISSUE TITLE
Fetching details from automic engine using java API

### ISSUE THREAD

**Issue by abhiz9711** [brendanSapience/UC4-Automic-Java-API-Getting-Started#1]
Hi Brendan,

I have few quires on fetching the details from Automic Engine from java API. These are my few quires.

1) Can we read an vara in automic from java API??
2)Can we able to fetch Agent status of an particular client from java API??

Please help me out in doing it, so that it will be very useful to me in future.

Looking froward to hear from you.

Thanks in advance :)

**Comment by brendanSapience** [comment]
Hi,

I no longer support any code related to UC4 / Automic products as I am no longer affiliated with the company.
